### ISSUE TITLE
gh-pages-deploy

### ISSUE THREAD

**Issue by HukakHePak** [guz86/yukids-task#2]
Привет, есть возможность сделать деплой на gh-pages? 
Так удобнее смотреть

Если долго или нет желания, может позже склонирую, скачаю нужную версию ноды и запущу

**Comment by guz86** [comment]
> Привет, есть возможность сделать деплой на gh-pages? Так удобнее смотреть
> 
> Если долго или нет желания, может позже склонирую, скачаю нужную версию ноды и запущу

https://yukids-task.vercel.app/

**Comment by HukakHePak** [comment]
Если интересно, могу оставить фидбек по тестовому

**Comment by guz86** [comment]
> Если интересно, могу оставить фидбек по тестовому

можешь

**Comment by HukakHePak** [comment]
По порядку

Оформлено красиво, темы меняются прикольно. Удивило что даже косточки двигаются, правда почему-то только верхние. И не прикольно, что они отталкиваются через margin.

Переключатели, отрицательных нет, но по дефолту ноль. Когда меняю - исчезает все, пока не натыкаю нужное

По коду, константы по типу startConfig в компонентах не особо нужны.  Да и в целом не понятно, к чему такая сложная структура, если функционала нет. Тут еще замечание, что разделитель абакуса - это горизонтальная полоска, а не две части под ней.
Очень сильно смутило, что нет компонента под инпуты с длинным className, еще и с логикой. Аналогично с компонентами для косточек

За оформление определенно лайк, я оценил. За код такое, не подход реакта

**Comment by guz86** [comment]
> По порядку 
спасибо за фидбек, да вроде простая структура, я бы даже сказал примитивная, за пару часов накидал по тз. Один компонент вынес чтобы  можно было косточки подергать, мне было просто интересно, это можно вообще не смотреть, этого не было в тз. Отрицательные переключатели их и не было в тз. Старт конфиг я предполагал что будут с апи данные загружаться, дефолтный конфиг сделал, хотя мог не делать, опять же мой интерес. Про горизонтальную полоску тоже в тз не слова. Я так понял из тз надо два инпута и чтобы элементы разделялись посередине, разбивать на компоненты такой простой компонент я не стал, тут согласен. Я хотел изначально по фсд сделать. Дробить на компоненты 100 строк кода, когда не известно будут ли они периспользоваться такое себе решение.
